name: Keep Website Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping website
        run: |
          curl -I --max-time 30 https://www.kalyanienterprises.com
