name: Keep Render App Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Keep Render app alive
        run: |
          curl -L --fail --silent --show-error \
            --max-time 30 \
            https://kalyanienterprises.onrender.com/health || true
